import Head from "next/head";
import { useEffect, useState } from "react";

const Home = () => {
  const [docked, setDocked] = useState(false);
  const [loggedIn, setLoggedIn] = useState(false);
  const [key, setKey] = useState("");

  useEffect(() => {
    const script = document.createElement("script");
    script.src = "https://js.jotform.com/JotForm.js";
    script.async = true;
    document.body.appendChild(script);
    setDocked(true);

    //@ts-ignore
    if (window.JF) {
      //@ts-ignore
      console.warn(JF.getAPIKey());
    }

    return () => {
      document.body.removeChild(script);
    };
  }, []);

  const login = () => {
    //@ts-ignore
    JF.login((response) => {
      setLoggedIn(true);
    });
  };

  const logout = () => {
    //@ts-ignore
    JF.logout((response) => {
      setLoggedIn(false);
    });
  };

  const getKey = () => {
    //@ts-ignore
    const x = JF.getAPIKey();
    console.warn(x);
    setKey(x);
  };

  const getForms = async () => {
    // const res = await axios.get("https://api.jotform.com/user/forms", {
    //   headers: { APIKEY: key, "Access-Control-Allow-Origin": true },
    // });
    // console.warn(res.data);
    //@ts-ignore
    JF.getForms(function (response) {
      console.warn(response);
    });
  };

  useEffect(() => {
    //@ts-ignore
    if (!window.JF) {
      return;
    }
    //@ts-ignore
    setKey(JF.getAPIKey());
  }, [loggedIn, docked]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={login}>Login</button>
      <button onClick={logout}>Logout</button>
      <button onClick={getKey}>Get Key</button>
      <button onClick={getForms}>Get Forms</button>
      <div>{key}</div>
    </div>
  );
};

export default Home;
